---
- name: Get Device Facts
  hosts: PHL-A1-FW2
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  tasks:
    - name: Checking NETCONF connectivity
      wait_for:
        host: "PHL-A1-FW2"
        port: 830
        timeout: 5

    - name: Retrieving information from devices running Junos OS
      juniper_junos_facts:
        host: "PHL-A1-FW2"

    - name: Print version
      debug:
        var: junos.hostname , junos.serialnumber , junos.version , junos.model
